name: release
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    with:
      node-version: '[20, 22]'

  release:
    uses: justland/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit

  docgen:
    permissions:
      contents: write
    uses: justland/.github/.github/workflows/pnpm-docs.yml@main
    needs: release